#!/bin/bash
# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

LOG=/tmp/dhclient-script.log

function log() {
  echo "$(date)" "$@" >>"${LOG}"
}

log "reason: ${reason}"

case "${reason}" in
  PREINIT)
    log "interface: ${interface}"
    ifconfig "${interface}" up
    ;;
  BOUND)
    log "interface: ${interface}"
    log "new_ip_address: ${new_ip_address}"
    log "new_subnet_mask: ${new_subnet_mask}"
    ifconfig "${interface}" "${new_ip_address}"
    ifconfig "${interface}" netmask "${new_subnet_mask}"
    ;;
esac
