runtime: python38

entrypoint:
  gunicorn -b :$PORT cros.factory.probe_info_service.app_engine.main:app

instance_class: F2
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: 500ms

inbound_services:
- warmup

handlers:
- url: /_ah/stubby/.*
  script: auto

- url: /_ah/warmup
  script: auto
