#!/usr/bin/env python3
# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""A fake runtime probe implemnetation to help verify the runtime probe wrapper.

It simply performs the following logic:
*   If `--to_stdout` is specified, the script dumps the value of the environment
    variable `FAKE_RUNTIME_PROBE_STDOUT` to stdout.
*   If `--verbosity_level` is set to positive values, the script dumps the probe
    config payload to stderr.
"""

import argparse
import sys
import os


def main():
  ap = argparse.ArgumentParser()
  ap.add_argument('--verbosity_level', default=0, type=int)
  ap.add_argument('--to_stdout', action='store_true')
  ap.add_argument('--config_file_path', default='')
  args = ap.parse_args()

  if args.to_stdout:
    # Probed result is controlled by the tester.
    print(os.getenv('FAKE_RUNTIME_PROBE_STDOUT', ''))

  if args.verbosity_level > 0:
    # Standard error contains the source material passed from the wrapper.
    with open(args.config_file_path, 'r', encoding='utf-8') as f:
      sys.stderr.write(f.read())

  sys.exit(int(os.getenv('FAKE_RUNTIME_PROBE_RETURN_CODE', '0')))


if __name__ == '__main__':
  main()
