# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# -*- coding: utf-8 -*-
# Generated by Django 3.1 on 2023-05-10 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('backend', '0018_auto_20210105_1152'),
  ]

  operations = [
      migrations.AddField(
          model_name='domeconfig',
          name='version_check_enabled',
          field=models.BooleanField(default=True),
      ),
  ]
