# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/reg_code.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/reg_code.proto\"E\n\x07\x43ontent\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x0c\x12\x1c\n\tcode_type\x18\x02 \x02(\x0e\x32\t.CodeType\x12\x0e\n\x06\x64\x65vice\x18\x03 \x01(\t\"6\n\x07RegCode\x12\x19\n\x07\x63ontent\x18\x01 \x02(\x0b\x32\x08.Content\x12\x10\n\x08\x63hecksum\x18\x02 \x02(\x03*>\n\x08\x43odeType\x12\x0e\n\nGROUP_CODE\x10\x00\x12\x0f\n\x0bUNIQUE_CODE\x10\x01\x12\x11\n\rONE_TIME_CODE\x10\x02')

_CODETYPE = DESCRIPTOR.enum_types_by_name['CodeType']
CodeType = enum_type_wrapper.EnumTypeWrapper(_CODETYPE)
GROUP_CODE = 0
UNIQUE_CODE = 1
ONE_TIME_CODE = 2


_CONTENT = DESCRIPTOR.message_types_by_name['Content']
_REGCODE = DESCRIPTOR.message_types_by_name['RegCode']
Content = _reflection.GeneratedProtocolMessageType('Content', (_message.Message,), {
  'DESCRIPTOR' : _CONTENT,
  '__module__' : 'proto.reg_code_pb2'
  # @@protoc_insertion_point(class_scope:Content)
  })
_sym_db.RegisterMessage(Content)

RegCode = _reflection.GeneratedProtocolMessageType('RegCode', (_message.Message,), {
  'DESCRIPTOR' : _REGCODE,
  '__module__' : 'proto.reg_code_pb2'
  # @@protoc_insertion_point(class_scope:RegCode)
  })
_sym_db.RegisterMessage(RegCode)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CODETYPE._serialized_start=151
  _CODETYPE._serialized_end=213
  _CONTENT._serialized_start=24
  _CONTENT._serialized_end=93
  _REGCODE._serialized_start=95
  _REGCODE._serialized_end=149
# @@protoc_insertion_point(module_scope)
